package com.accenture.accademy.spring.security.repositories;

import com.accenture.accademy.spring.security.model.Employee;
import com.accenture.accademy.spring.security.model.Project;
import org.springframework.data.repository.CrudRepository;

import java.util.List;

/**
 * Repository managing Projects persistence with Spring Data.
 * @see CrudRepository
 */
public interface ProjectRepository extends CrudRepository<Project, String> {
    /**
     * Find all projects having a given lead.
     * Implementation of method is auto generated by Spring Data.
     */
    List<Project> findByLead(Employee employee);
}